# Comandos de gestión del proyecto CineFlow

install:
	cd backend && npm install

run-backend:
	cd backend && npm run dev

lint:
	cd backend && npx eslint src/**/*.js

.PHONY: install run-backend lint