sonar.projectKey=CineFlow-SGC
sonar.projectName=CineFlow-SGC
sonar.projectVersion=1.0.0

# Rutas de origen del código y tests
sonar.sources=src
sonar.tests=src/tests
sonar.exclusions=src/tests/**, node_modules/**

# Enlaces a los reportes de cobertura generados por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml